### PR TITLE
Sync before exiting a cilk_scope with a non-compound statement body

### LINKED ISSUE #319: cilk_scope without braces fails to sync
This test program
```
#include <stdio.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
  cilk_scope for (int i = 0; i < argc; ++i)
    cilk_spawn { fprintf(stdout, "%s\n", argv[i]); usleep(100); }
  return 0;
}
```
crashes with an assertion failure when run on more than one thread:
```
cilk assertion failed: __cilkrts_synced(sf)
```
Adding braces around the body of the `cilk_scope` fixes the problem.

The `usleep` call is to make sure work is stolen.

### PR DESCRIPTION
**Pull request by VoxSciurorum**
Fixes #319.

### CODE REVIEW

File: clang/lib/CodeGen/CGCilk.cpp [hunk 1]
```diff
@@ -471,22 +471,24 @@ void CodeGenFunction::EmitCilkScopeStmt(const CilkScopeStmt &S) {
...
-    if (BodyIsCompoundStmt)
+    if (isa<CompoundStmt>(S.getBody())) {
+      SyncRegionRAII SyncReg(*this);
       ScopeIsSynced = true;
-
-    // Emit the spawned statement.
-    EmitStmt(S.getBody());
+      EmitStmt(S.getBody());
+    } else {
+      PushSyncRegion()->addImplicitSync();
```
Comment (neboat) [inline clang/lib/CodeGen/CGCilk.cpp]: It took me a while to figure out why these changes were necessary, given that the `SyncRegionRAII` is meant to handle pushing and popping of sync regions.

I think the simpler approach to resolving this issue is to set `ScopeIsSynced` to `true` before pushing the `TapirRuntimeEndCleanup`, e.g., on line 472.  That flag is used to ensure that implicit syncs and cleanups/destructors are ordered correctly within a lexical scope.  Does that approach work for your tests?

**Comment by VoxSciurorum** [comment]
The second version crashes on this input, processed by the first version:
```cpp
void f()
{
  extern void function(void);
  cilk_scope { cilk_scope cilk_spawn { function(); } }
}
```

**Comment by neboat** [comment]
I see.  It looks like we also need to ensure the `sync` is inserted before any `taskframe.end` intrinsics.

Does it work if we move the `ScopeIsSynced = true` assignment to line 468, before the `TaskFrameScope` RAII variable is defined?  Does anything else break in that case?

**Comment by VoxSciurorum** [comment]
Moving the assignment earlier worked.  I added another test for nested `cilk_scope`.
